version: "3.9"

services:
  api:
    build: .
    container_name: kopi_api
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    stdin_open: true
    tty: true
